[project]
name = "otus-pro"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "structlog (>=26.1.0,<27.0.0)",
]

[tool.poetry]
package-mode = true
packages = [{ include = "log_analyzer.py" }]
include = [
    { path = "templates", format = ["sdist", "wheel"]}
]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]

[tool.black]
line-length = 88
target-version=["py314"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.14"
disallow_untyped_defs = true

[tool.pytest.ini_options]
pythonpath = ["."]

[project.scripts]
log-analyzer = "log_analyzer:cli"

[build-system]
requires = ["poetry-core>=2.2.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
